import os
import httpx
import asyncio
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

class UTTracker:
    def __init__(self):
        self.moodle_session = os.getenv("MOODLE_SESSION")
        self.moodle_sesskey = os.getenv("MOODLE_SESSKEY")
        self.myut_token = os.getenv("MYUT_TOKEN")
        self.wa_api = os.getenv("WHATSAPP_API")
        self.boss_wa = os.getenv("BOSS_WHATSAPP")
        
        # Mapping Matkul ke Group ID (Auto-generated by L.I.F.A.)
        self.group_map = {
            "Kalkulus Diferensial": "120363424755720191@g.us",
            "Sistem Informasi": "120363426280722869@g.us",
            "Statistika": "120363426301696334@g.us",
            "Infrastruktur TI": "120363407647958870@g.us",
            "Bahasa Indonesia": "120363424779208094@g.us"
        }
        self.default_group = "120363427246480048@g.us" # Main Community Group

    async def get_elearning_deadlines(self):
        url = f"https://elearning.ut.ac.id/lib/ajax/service.php?sesskey={self.moodle_sesskey}&info=core_calendar_get_action_events_by_timesort"
        headers = {
            "Content-Type": "application/json",
            "Cookie": f"MoodleSession={self.moodle_session}",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36"
        }
        payload = [{"index": 0, "methodname": "core_calendar_get_action_events_by_timesort", "args": {"limitnum": 10}}]
        
        async with httpx.AsyncClient() as client:
            try:
                resp = await client.post(url, json=payload, headers=headers)
                data = resp.json()
                if data and not data[0].get("error"):
                    return data[0]["data"]["events"]
            except Exception as e:
                print(f"API Error: {e}")
        return []

    async def send_whatsapp(self, chat_id, text):
        payload = {
            "chatId": chat_id,
            "message": text
        }
        try:
            async with httpx.AsyncClient() as client:
                await client.post(self.wa_api, json=payload)
        except Exception as e:
            print(f"Failed to send WA to {chat_id}: {e}")

    async def run_check(self):
        print(f"[{datetime.now()}] Checking deadlines...")
        events = await self.get_elearning_deadlines()
        
        if not events:
            await self.send_whatsapp(self.default_group, "Halo Boss! L.I.F.A. cek tidak ada deadline mendesak hari ini. (╹▽╹)")
            return

        for ev in events:
            course_name = ev['course']['fullname']
            
            # Determine target group
            target_id = self.default_group
            for key, gid in self.group_map.items():
                if key in course_name:
                    target_id = gid
                    break
            
            # Format message
            status = "⏳ UPCOMING" if not ev.get('overdue') else "⚠️ OVERDUE"
            deadline_str = "10 Mei 2026, 23:59 WIB" if not ev.get('overdue') else "Sudah Lewat"
            
            msg = f"🚨 *L.I.F.A. ACADEMIC ALERT* 🚨\n\n"
            msg += f"📌 *{ev.get('activityname', ev.get('name', 'Tugas'))}*\n"
            msg += f"📊 Status: {status}\n"
            msg += f"⏰ Deadline: {deadline_str}\n"
            msg += f"🔗 Link: {ev.get('url', 'https://elearning.ut.ac.id/my/')}\n\n"
            msg += "Ayo dikerjakan Boss! L.I.F.A. stand-by buat bantu. (｡•̀ᴗ-)✧"
            
            await self.send_whatsapp(target_id, msg)
            # Juga kirim ringkasan ke grup utama
            await self.send_whatsapp(self.default_group, f"📢 Alert baru di grup *{course_name}*!")

if __name__ == "__main__":
    tracker = UTTracker()
    asyncio.run(tracker.run_check())
